import { supabase } from './supabase';

export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

interface GrokChatPayload {
  clientId: string;
  courseId: string;
  messages: ChatMessage[];
}

/**
 * Dispatches the current message history and context filters to the grok-chat Edge Function.
 * @returns The final string response generated by Grok AI, anchored to the course knowledge base.
 */
export const sendChatMessageToGrok = async ({
  clientId,
  courseId,
  messages
}: GrokChatPayload): Promise<string> => {
  try {
    // 1. Verify there is a live, valid session before executing the invocation
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) {
      throw new Error('Action denied: Session token is missing or expired.');
    }

    // 2. Invoke the serverless function securely using the built-in functions utility client.
    // The SDK automatically attaches the active user's Access Token (JWT) in the headers.
    const { data, error } = await supabase.functions.invoke('grok-chat', {
      method: 'POST',
      body: {
        clientId,
        courseId,
        messages,
      },
    });

    if (error) {
      throw new Error(`Edge Function Execution Error: ${error.message}`);
    }

    if (!data || !data.response) {
      throw new Error('Received unexpected payload structure from the EdAI inference server.');
    }

    return data.response;
  } catch (error: any) {
    console.error('Failed to parse runtime AI response stream context:', error);
    throw error;
  }
};


/**
 * example:
 * 
 * import { useState } from 'react';
import { sendChatMessageToGrok, ChatMessage } from './services/grokChatService';

// Inside your main React component block:
const [messages, setMessages] = useState<ChatMessage[]>([]);
const [loading, setLoading] = useState(false);

const onSendMessage = async (textInput: string) => {
  if (!textInput.trim()) return;

  const updatedMessages: ChatMessage[] = [...messages, { role: 'user', content: textInput }];
  setMessages(updatedMessages);
  setLoading(true);

  try {
    const aiAnswer = await sendChatMessageToGrok({
      clientId: 'CURRENT_CLIENT_UUID', // e.g., acme-corp-id
      courseId: 'ACTIVE_COURSE_UUID', // Passes the active course ID dynamically
      messages: updatedMessages,
    });

    setMessages((prev) => [...prev, { role: 'assistant', content: aiAnswer }]);
  } catch (err: any) {
    console.error("Chat routing error:", err.message);
  } finally {
    setLoading(false);
  }
};

 */